**19BCE7478 - Nittoor Vishnu Bharadwaj**

---

In [19]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import accuracy_score
titanic = pd.read_csv("/content/titanic.csv")
titanic.Age=titanic.Age.fillna(titanic.Age.mean())
d = {'male': 1, 'female': 0}
titanic['Sex'] = titanic['Sex'].map(d)
print(titanic)

     Survived  Pclass  Sex       Age
0           0       3    1  34.50000
1           1       3    0  47.00000
2           0       2    1  62.00000
3           0       3    1  27.00000
4           1       3    0  22.00000
..        ...     ...  ...       ...
413         0       3    1  30.27259
414         1       1    0  39.00000
415         0       3    1  38.50000
416         0       3    1  30.27259
417         0       3    1  30.27259

[418 rows x 4 columns]


In [14]:
#Train Test Split
from sklearn.model_selection import train_test_split
X=titanic[['Pclass', 'Sex', 'Age']]
y=titanic['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

rfcl = RandomForestClassifier(n_estimators=10)
rfc2 = RandomForestClassifier(n_estimators=50) 
rfc3 = RandomForestClassifier(n_estimators=100) 
rfc4 = RandomForestClassifier(n_estimators=150) 
rfc5 = RandomForestClassifier(n_estimators=200)

rfcl.fit(X_train, y_train) 
rfc2.fit(X_train, y_train)
rfc3.fit(X_train, y_train) 
rfc4.fit(X_train, y_train) 
rfc5.fit(X_train, y_train)
predictionsl = rfcl.predict(X_test) 
predictions2 = rfc2.predict(X_test) 
predictions3 = rfc3.predict(X_test) 
predictions4 = rfc4.predict(X_test) 
predictions5 = rfc5.predict(X_test)

print(" For 10 trees:" , classification_report(y_test, predictionsl)) 
print(" For 50 trees:", classification_report(y_test, predictions2))
print(" For 100 trees:", classification_report(y_test, predictions3)) 
print(" For 150 trees:", classification_report(y_test, predictions4)) 
print(" For 200 trees:", classification_report(y_test, predictions5))

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

 For 10 trees:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        41

    accuracy                           1.00       126
   macro avg       1.00      1.00      1.00       126
weighted avg       1.00      1.00      1.00       126

 For 50 trees:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        41

    accuracy                           1.00       126
   macro avg       1.00      1.00      1.00       126
weighted avg       1.00      1.00      1.00       126

 For 100 trees:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        85
           1       1.00      1.00      1.00        41

    accuracy                           1.00       126
   macro avg       1.00      1.00      1.00       126
weighted avg       1.00     

In [20]:
print("Accuracy for 10 trees: ", accuracy_score(y_test, predictionsl)) 
print("Accuracy for 50 trees: ", accuracy_score(y_test, predictions2)) 
print("Accuracy for 100 trees: ", accuracy_score(y_test, predictions3)) 
print("Accuracy for 150 trees: ", accuracy_score(y_test, predictions4)) 
print("Accuracy for 200 trees: ", accuracy_score(y_test, predictions5)) 
print()

Accuracy for 10 trees:  1.0
Accuracy for 50 trees:  1.0
Accuracy for 100 trees:  1.0
Accuracy for 150 trees:  1.0
Accuracy for 200 trees:  1.0



In [21]:
print("Confusion Matrix for 10 trees:\n", confusion_matrix(y_test, predictionsl)) 
print("Confusion Matrix for 50 trees:\n", confusion_matrix(y_test, predictions2)) 
print("Confusion Matrix for 100 trees:\n", confusion_matrix(y_test, predictions3)) 
print("Confusion Matrix for 150 trees:\n", confusion_matrix(y_test, predictions4)) 
print("Confusion Matrix for 200 trees:\n", confusion_matrix(y_test, predictions5))



Confusion Matrix for 10 trees:
 [[85  0]
 [ 0 41]]
Confusion Matrix for 50 trees:
 [[85  0]
 [ 0 41]]
Confusion Matrix for 100 trees:
 [[85  0]
 [ 0 41]]
Confusion Matrix for 150 trees:
 [[85  0]
 [ 0 41]]
Confusion Matrix for 200 trees:
 [[85  0]
 [ 0 41]]


In [22]:
print("The Random Forest having highest accuracy is: ", accuracy_score(y_test, predictions5)) 
print()
print(confusion_matrix(y_test, predictions5))


The Random Forest having highest accuracy is:  1.0

[[85  0]
 [ 0 41]]


In [9]:
confusion_matrix(y_test, clf.predict(X_test))

array([[83,  0],
       [ 0, 43]])

In [10]:
#Accuracy
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0
